version: '3.8'

services:

  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - databases

  pgadmin4:
    image: dpage/pgadmin4:4.24
    restart: always
    env_file:
      - ./.env
    ports:
      - 8080:80
    networks:
      - databases

networks:
  databases:
    name: databases